### ISSUE TITLE
💡 [需求] <希望添加禁止系统莫奈取色的功能>

### ISSUE THREAD

**Issue by freedomspiritJohn** [saraSakuHj/HyperCeiler#10]
### 需求内容

虽然有人喜欢莫奈取色，但是也有人不喜欢莫奈取色，因为他老是会变颜色，有时候是不好分辨的颜色有时候是不喜欢的颜色。而且因为变来变去，图标都不好找

### 简单例子

暂无

**Comment by Sevtinge** [comment]
系统界面-其他-自定义主题色

**Comment by freedomspiritJohn** [comment]
> 系统界面-其他-自定义主题色

但这不是APP原来自己的颜色吧，还是自定义后的主题色

**Comment by Sevtinge** [comment]
app自己的颜色没有明确定义，如果你是指图标颜色，直接在桌面改就行

**Comment by Sevtinge** [comment]
> > 系统界面-其他-自定义主题色
> 
> 但这不是APP原来自己的颜色吧，还是自定义后的主题色

app自己的颜色没有明确定义，如果你是指图标颜色，直接在桌面改就行
