### ISSUE TITLE
5G模式开关无法在控制中心内显示

### ISSUE THREAD

**Issue by HoneyWhiteCloud** [saraSakuHj/HyperCeiler#15]
### 问题描述

cemiuiler系统界面里面的 通知与控制中心内的5G开关无法在控住中心内显示，但gms按钮可以正常显示，大概两个之前的版本可以正常使用，更新后就不能用了。(已重启过作用域)

### 模块日志

None

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

https://github.com/saraSakuHj/HyperCeiler/assets/96010373/fa17981e-3faa-4476-a9bc-8b7c4a72158e

![Screenshot_2023-11-02-17-12-06-474_com miui securitycenter](https://github.com/saraSakuHj/HyperCeiler/assets/96010373/d779915b-7eec-4162-afa1-8db81d7bb364)

### 机型

Xiaomi 12 Pro

### MIUI 版本

MIUI13

### Android 版本

Android 12

### HyperCeiler 版本

1.3.130_20231101

**Comment by HChenX** [comment]
更新最新版hyperceiler

**Comment by HoneyWhiteCloud** [comment]
hyperceiler我未能找到发行版，cemiuiler最新版也不行

**Comment by HChenX** [comment]
> hyperceiler我未能找到发行版，cemiuiler最新版也不行

电报群 https://t.me/cemiuiler_beta
