### ISSUE TITLE
🐛 [BUG] <全面屏键盘优化>功能异常

### ISSUE THREAD

**Issue by EscapeA** [saraSakuHj/HyperCeiler#16]
### 问题描述

横屏状态下显示白条遮挡部分内容
![Screenshot_2023-11-03-08-33-09-734_com tencent mm](https://github.com/saraSakuHj/HyperCeiler/assets/53213938/c7a079df-bab2-415d-a9b0-4d63de08a9de)

### 模块日志

无崩溃问题

### 复现步骤

```bash
横屏下,打开微信,选择联系人,点击输入框唤醒输入法,出现白条遮挡微信输入框
```

### 问题截图

白条
![Screenshot_2023-11-03-08-33-09-734_com tencent mm](https://github.com/saraSakuHj/HyperCeiler/assets/53213938/d863af2e-2ba2-4a38-9546-c027f08472a0)

### 机型

K60

### MIUI 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

1.3.130_20231101

**Comment by Sevtinge** [comment]
有没有可能这个是输入框（

**Comment by EscapeA** [comment]
并不是输入框

**Comment by HChenX** [comment]
无法复现
