### ISSUE TITLE
希望加入桌面阉割掉的切换上一个应用功能

### ISSUE THREAD

**Issue by Mubai-meng** [saraSakuHj/HyperCeiler#19]
### 需求内容

从屏幕两侧向内滑动并停顿，快速切换上一个应用，这样方便晚上躺床上玩手机切换应用。
此功能代码还在，只是把开关UI给阉割了，希望能加回来！

### 实现思路&截图

![3f4ec6d1f9229ad8804678746d2406bf](https://github.com/saraSakuHj/HyperCeiler/assets/86759349/0a5aa0ab-4224-4f3f-a39d-7aa96d6f8172)

### 简单例子

从屏幕两侧向内滑动并停顿，快速切换上一个应用

**Comment by HChenX** [comment]
已经加入

**Comment by HChenX** [comment]
顺带提一句，代码已经被miui删掉了，是看tat的桌面补充回来的。

**Comment by Mubai-meng** [comment]
> 顺带提一句，代码已经被miui删掉了，是看tat的桌面补充回来的。

非常感谢！

**Comment by zion965123** [comment]
这个功能应用在系统系统RELEASE-4.39.14.7522-11041919版上使用一次后，下一次普通内拉返回大概率无效，再下一次才生效，然后在后续打开另一个应用时会出现自动出现后退效果(也就是第一次内拉返回生效了)。红米K50u，澎湃1.0.14移植版。

**Comment by HChenX** [comment]
> 这个功能应用在系统系统RELEASE-4.39.14.7522-11041919版上使用一次后，下一次普通内拉返回大概率无效，再下一次才生效，然后在后续打开另一个应用时会出现自动出现后退效果(也就是第一次内拉返回生效了)。红米K50u，澎湃1.0.14移植版。

正常
