### ISSUE TITLE
💡 [需求] <去掉搜狗输入法小米版限制>

### ISSUE THREAD

**Issue by h88782481** [saraSakuHj/HyperCeiler#20]
### 需求内容

能不能增加一条hook搜狗输入法小米版，去掉小米输入法的剪切板条数限制和复制的字数限制，同时如果搜狗输入法小米版开启了隐私输入模式会禁止剪切板使用，能不能也把这个限制去除

### 简单例子

剪切板无上限，复制的字数无限制，开启隐私输入模式后正常使用剪切板

**Comment by HChenX** [comment]
大佬自己写，呜呜

**Comment by HChenX** [comment]
> 额，我不是什么大佬啊，我上班比较忙，没时间 我可以提供一下hook点com.sohu.inputmethod.clipboard.l这个类的d方法 ![image](https://user-images.githubusercontent.com/54714341/281018654-df583417-1ece-4451-86f4-c8f8f9a12517.png) 根据代码，可以得到，如果list为空或者小于150条就啥也不干，如果大于了150条就会把最开始的一条删了，把下边delete去掉就能破解掉150条的限制，复制字数的限制我并不太清楚它限制了多少条，所以没找到hook点

好，交给我了

**Comment by h88782481** [comment]
> > 额，我不是什么大佬啊，我上班比较忙，没时间 我可以提供一下hook点com.sohu.inputmethod.clipboard.l这个类的d方法 ![image](https://user-images.githubusercontent.com/54714341/281018654-df583417-1ece-4451-86f4-c8f8f9a12517.png) 根据代码，可以得到，如果list为空或者小于150条就啥也不干，如果大于了150条就会把最开始的一条删了，把下边delete去掉就能破解掉150条的限制，复制字数的限制我并不太清楚它限制了多少条，所以没找到hook点
> 
> 好，交给我了

嘿嘿，辛苦了

**Comment by h88782481** [comment]
找到字数限制的hook点了com.sohu.inputmethod.clipboard.t这个类下的a方法
![image](https://github.com/saraSakuHj/HyperCeiler/assets/54714341/25de5a9c-07c5-4fa8-a246-0d755e20066f)
点进去，然后搜索5000的十六进制“0x1388”
然后改成改成9999的十六进制“0x2710”，别超过五位数，因为据说会乱码
