### ISSUE TITLE
💡 [需求] <移除部分应用小窗状态下上方的黑条>

### ISSUE THREAD

**Issue by lswlc33** [saraSakuHj/HyperCeiler#22]
### 需求内容

![Image_1699201922805](https://github.com/saraSakuHj/HyperCeiler/assets/86835895/53242a37-646f-4f20-8262-6a61c3537fc4)
如图，该为典型的两应用，王者上方没有遮挡，并且图标可以点击，但是x穷铁道上方有一个灰条，会影响点击与观感，phigros，bh3等应用都有此情况

### 实现思路&截图

不知道

### 简单例子

正常的应用有抖音，云原神，横屏与竖屏的播放哔哩哔哩，

**Comment by mu7220** [comment]
做不了，本身这里是需要应用自身适配的，强行去目测小滑条估计也会寄
