### ISSUE TITLE
🐛 [BUG] <通知图标最大数量失效>

### ISSUE THREAD

**Issue by yzd201886870** [saraSakuHj/HyperCeiler#29]
### 问题描述

把通知图标数量改为6还是最多显示3个

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2023-11-09-11-21-08-073_com sevtinge hyperceiler](https://github.com/saraSakuHj/HyperCeiler/assets/88877231/b10ae91a-520e-472e-bf4b-fbb8bfd0c0b7)

### 机型

xiaomi

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

MIUI14.0.6

**Comment by HChenX** [comment]
发日志谢谢

**Comment by yzd201886870** [comment]
> 发日志谢谢

https://www.123pan.com/s/KodlVv-BMhyv.html

**Comment by HChenX** [comment]
> > 发日志谢谢
> 
> https://www.123pan.com/s/KodlVv-BMhyv.html

未找到相关日志，尝试重新设置功能，并且不要打开模块禁用详细日志的功能。

**Comment by yzd201886870** [comment]
> > > 发日志谢谢
> > 
> > https://www.123pan.com/s/KodlVv-BMhyv.html
> 
> 未找到相关日志，尝试重新设置功能，并且不要打开模块禁用详细日志的功能。

https://www.123pan.com/s/KodlVv-IMhyv.html

**Comment by HChenX** [comment]
> > > > 发日志谢谢
> > > 
> > > 
> > > https://www.123pan.com/s/KodlVv-BMhyv.html
> > 
> > 
> > 未找到相关日志，尝试重新设置功能，并且不要打开模块禁用详细日志的功能。
> 
> https://www.123pan.com/s/KodlVv-IMhyv.html

修好了
