### ISSUE TITLE
5g开关失效

### ISSUE THREAD

**Issue by YansongChen** [saraSakuHj/HyperCeiler#31]
### 问题描述

手机型号k30pro,miui版本14.0.5，西米露1.2.128还能用，129和130版本5g开关失效，调不出来。

### 模块日志

无

### 复现步骤

```bash
1.打开西米露
2.打开5g开关
3.通知栏快捷开关无反应
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2023-11-10-15-49-02-449_com sevtinge cemiuiler](https://github.com/saraSakuHj/HyperCeiler/assets/23722728/d20a17d2-e514-4a6b-9438-364448608b6f)

### 机型

红米k30pro

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 12

### HyperCeiler 版本

1.3.129和1.3.130

**Comment by HChenX** [comment]
给日志谢谢

**Comment by HChenX** [comment]
等你发日志再说

**Comment by YansongChen** [comment]
把lsp日志导出来吗

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 中午1:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [saraSakuHj/HyperCeiler] 5g开关失效 (Issue #31)




 
等你发日志再说

**Comment by HChenX** [comment]
> 把lsp日志导出来吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月11日(周六) 中午1:02 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [saraSakuHj/HyperCeiler] 5g开关失效 (Issue #31) 等你发日志再说 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是的

**Comment by YansongChen** [comment]
今天提取的日志，手机是k30pro，系统a12,miui14.0.5，西米露版本130



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 下午4:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [saraSakuHj/HyperCeiler] 5g开关失效 (Issue #31)




  
把lsp日志导出来吗
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年11月11日(周六) 中午1:02 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [saraSakuHj/HyperCeiler] 5g开关失效 (Issue #31) 等你发日志再说 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
是的
