### ISSUE TITLE
🐛 [BUG] <允许对任意应用进行截屏和录屏功能失效>

### ISSUE THREAD

**Issue by DHHHhhhe** [saraSakuHj/HyperCeiler#50]
### 问题描述

系统框架-其他-允许截屏功能失效

### 模块日志

无

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)
![cb4805f40f92dc0635ab09947fe3778](https://github.com/saraSakuHj/HyperCeiler/assets/48945303/c082a034-91e3-4da6-8f6e-91052246bd5b)

### 机型

xiaomi14

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231113_6911a210

**Comment by HChenX** [comment]
等上游更新

**Comment by Sevtinge** [comment]
让我们期待西大师的更新

**Comment by Sevtinge** [comment]
修了 并且提交到了上游
