### ISSUE TITLE
🔌 [移植] <移动面板5g开关>

### ISSUE THREAD

**Issue by yyds1314666** [saraSakuHj/HyperCeiler#52]
### 仓库地址

https://github.com/Xposed-Modules-Repo/com.qingyu.mi5g

### 移植内容

在miui移动网络面板中添加5g开关，酷安@yangyiyu08大佬的，更加合理美观

### 相关描述&截图

![Screenshot_2023-11-13-21-38-29-864_info muge appshare](https://github.com/saraSakuHj/HyperCeiler/assets/111941219/89772e5b-d784-4478-ac4b-4b28c0bafba8)

**Comment by HChenX** [comment]
不做！！
