### ISSUE TITLE
🐛 [BUG] <Android14允许不受信触控功能无效>

### ISSUE THREAD

**Issue by xinghe6** [saraSakuHj/HyperCeiler#54]
### 问题描述

如题

### 模块日志

[LSPosed_2023-11-14T19_17_13.388590.zip](https://github.com/saraSakuHj/HyperCeiler/files/13348080/LSPosed_2023-11-14T19_17_13.388590.zip)

### 复现步骤

```bash
打开功能即可复现
```

### 问题截图

![Screenshot_2023-11-14-19-18-50-437_com sevtinge hyperceiler](https://github.com/saraSakuHj/HyperCeiler/assets/127053781/8bd7c953-26cb-49af-b6b5-e32c8526cf76)

### 机型

xiaomi 10 ultra

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231114_c21e7596 (132)

**Comment by HChenX** [comment]
好消息，似乎搞不了

**Comment by xinghe6** [comment]
尊嘟假嘟，那Android14这个是无解吗
