### ISSUE TITLE
🔌 [移植] <为冻结（pm disable）应用提供mipush通知接入>

### ISSUE THREAD

**Issue by Pik-4** [saraSakuHj/HyperCeiler#56]
### 仓库地址

https://github.com/Xposed-Modules-Repo/com.vivian8421.mipushenhance
https://github.com/vivian8421/MiPush-Enhance

### 移植内容

为pm disable冻结的应用提供mipush服务，防止消息遗漏。
注：参考模块不能在hyperos工作，但miui14工作正常。

**Comment by HChenX** [comment]
不做
